### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [FreezeYou/FreezeYou#187]
**您的功能请求是否与某些问题有关？如果有关请描述**  
请问是否可以将应用发布到 F-Droid?

**Comment by Playhi** [comment]
可以啊，需要我怎么操作吗？还是不用我动手，可以直接同步 GitHub 上的 Release？先前 #175 那个 Issue 似乎有个类似的意思，但是我没搞明白 :joy: 以及那次看了看似乎要先交一笔什么费用？总之当时没搞清楚到底什么情况 🤣



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月28日 22:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [FreezeYou/FreezeYou] F-Droid (Issue #187) |

您的功能请求是否与某些问题有关？如果有关请描述
请问是否可以将应用发布到 F-Droid?

**Comment by linsui** [comment]
F-Droid 是一个自由开源的应用商店，apk 将从本仓库的代码中构建。我会试着打包你的应用，如果没有问题就会发布。根据 F-Droid 的政策，需要你的同意。其他的就是技术问题，主要是要求所有依赖从源码构建，或者来自几个 maven。我看了一下代码似乎也没有专有依赖。请问 libs 中的两个 aar 是怎么构建的？

**Comment by tommynok** [comment]
> **您的功能请求是否与某些问题有关？如果有关请描述** 请问是否可以将应用发布到 F-Droid?

It seems that FrezeYou is already in F-Droid.
Or rather, in one of the repositories of F-Droid
https://android.izzysoft.de/repo/apk/cf.playhi.freezeyou

**Comment by linsui** [comment]
Yes, it's in the Izzy's repo which taks apk from github. I'd like to package it for the official repo which builds apks from source. Izzy's repo is good but the official repo has the most users.

**Comment by Playhi** [comment]
>  ...请问 libs 中的两个 aar 是怎么构建的？

`Tray(net.grandcentrix.tray.tray)` 是[这个(https://github.com/GCX-HCI/tray)](https://github.com/GCX-HCI/tray)，`aar` 是从 `JCenter` 搬下来的，因为 `JCenter` 要关了。
`MMKV`是自编译过的，来源是[这里(https://github.com/Tencent/MMKV)](https://github.com/Tencent/MMKV/)，目前的是基于 `dev` 分支构建的，后续应该就基于 `master(main)` 分支了，重新构建的版本中 `/Core/MMKVPredef.h` 文件有变更，第 25 + 26 行修改为： 
```
#define MMKV_DISABLE_CRYPT
#define MMKV_DISABLE_FLUTTER
```

**Comment by Playhi** [comment]
> Yes, it's in the Izzy's repo which taks apk from github. I'd like to package it for the official repo which builds apks from source. Izzy's repo is good but the official repo has the most users.

如果进到 F-droid 的 official repo，F-droid 的 official repo 是在什么情况下会同步更新呢？以及会对 IzzyOnDroid 的 repo 那边产生什么影响吗？之前看了下 IzzyOnDroid 那边的 FreezeYou 似乎是直接搬的 GitHub Release，签名也一致，不影响通过其他渠道更新，如果由 F-Droid 源码构建，签名是每个应用由 F-Droid 生成一个吗还是全部 F-droid 共用一个或是其他方案？

**Comment by linsui** [comment]
F-Droid 的官方存储库会自动从每个新的 tag 构建 apk，一般会在发布 release 之后两到三天更新，相比 Izzy 的库慢一点。两个库互不影响。启用哪个库是用户决定的，官方库在客户端中默认启用。一般 Izzy 会在应用进入主存储库后从他的库中移除，但也可以要求继续保留在他的库中。主存储库的 apk 是每个应用自动生成一个签名。

**Comment by Playhi** [comment]
> F-Droid 的官方存储库会自动从每个新的 tag 构建 apk，一般会在发布 release 之后两到三天更新，相比 Izzy 的库慢一点。两个库互不影响。启用哪个库是用户决定的，官方库在客户端中默认启用。一般 Izzy 会在应用进入主存储库后从他的库中移除，但也可以要求继续保留在他的库中。主存储库的 apk 是每个应用自动生成一个签名。

那这样的话，如果进了 `F-Droid 的官方存储库`，并且 Izzy 在 `自冻(FreezeYou)` 进入主存储库后从他的库中移除，那么之前使用 lzzy 库的用户很可能就会因为签名变更而无法平滑升级到新版本了，是这样吗？如果这样的话，我觉得很有必要`要求继续保留在他的库中`，这一步是在发布到 `F-Droid 的官方存储库` 的时候可以一并要求的吗？还是还需要什么额外的操作 :joy:

**Comment by Playhi** [comment]
如果进到 F-Droid 的 official repo 了的话给我个链接哈，到时把它和 Izzy 的库一起写到 FreezeYou 官网的下载页里。

**Comment by linsui** [comment]
> 那这样的话，如果进了 F-Droid 的官方存储库，并且 Izzy 在 自冻(FreezeYou) 进入主存储库后从他的库中移除，那么之前使用 lzzy 库的用户很可能就会因为签名变更而无法平滑升级到新版本了，是这样吗？如果这样的话，我觉得很有必要要求继续保留在他的库中，这一步是在发布到 F-Droid 的官方存储库 的时候可以一并要求的吗？还是还需要什么额外的操作 😂

我会在打包的时候请 Izzy 保留这个应用的。

> 如果进到 F-Droid 的 official repo 了的话给我个链接哈，到时把它和 Izzy 的库一起写到 FreezeYou 官网的下载页里。

好的，我之后会把两个存储库的徽标也贴在这里。

**Comment by Playhi** [comment]
> > 那这样的话，如果进了 F-Droid 的官方存储库，并且 Izzy 在 自冻(FreezeYou) 进入主存储库后从他的库中移除，那么之前使用 lzzy 库的用户很可能就会因为签名变更而无法平滑升级到新版本了，是这样吗？如果这样的话，我觉得很有必要要求继续保留在他的库中，这一步是在发布到 F-Droid 的官方存储库 的时候可以一并要求的吗？还是还需要什么额外的操作 joy
> 
> 我会在打包的时候请 Izzy 保留这个应用的。
> 
> > 如果进到 F-Droid 的 official repo 了的话给我个链接哈，到时把它和 Izzy 的库一起写到 FreezeYou 官网的下载页里。
> 
> 好的，我之后会把两个存储库的徽标也贴在这里。

OK，感谢 :joy:

**Comment by linsui** [comment]
请问最新的稳定版是哪个？我看到有一个 `V10.16(142)` 不知道是不是稳定版？

**Comment by Playhi** [comment]
10.15(141)，是最新的 release，2021年2月的。10.16(142) 这个 tag 是打错了的 :捂脸:

**Comment by linsui** [comment]
好的 :joy:

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10507

有一个 fdroidserver 的 bug 导致无法自动更新。我打包了最新的稳定版和 master，主要是为了可以抓取 fastlane 元数据，防止自动更新到 10.16。后续仅会自动更新到稳定版。

Tray 是从 jitpack 拉取的，MMKV 按照你的步骤进行了构建。

我想等下一个 tag 发布，以及自动更新的问题解决再合并。

**Comment by Playhi** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10507
> 
> 有一个 fdroidserver 的 bug 导致无法自动更新。我打包了最新的稳定版和 master，主要是为了可以抓取 fastlane 元数据，防止自动更新到 10.16。后续仅会自动更新到稳定版。
> 
> Tray 是从 jitpack 拉取的，MMKV 按照你的步骤进行了构建。
> 
> 我想等下一个 tag 发布，以及自动更新的问题解决再合并。

好的，十分感谢 :joy: 下一个 tag 估计一周内会发，到时候我在这个 issue 再喊一声 :grinning:

**Comment by linsui** [comment]
谢谢！

**Comment by Playhi** [comment]
> 谢谢！

新的 Release 释出了 :joy: 新春快乐～

**Comment by linsui** [comment]
新春快乐！fdroidserver 的 bug 还没解决，不过不影响构建，我更新一下然后就合并。

**Comment by linsui** [comment]
已合并！自动更新的问题之后会解决。大概两到三天内会进入存储库。主存储库徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/cf.playhi.freezeyouSome)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/cf.playhi.freezeyouSome)
```

IzzySoft 存储库的徽标

[<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png"
    alt="Get it on IzzyOnDroid"
    height="80">](https://apt.izzysoft.de/fdroid/index/apk/cf.playhi.freezeyou)

```
[<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png"
    alt="Get it on IzzyOnDroid"
    height="80">](https://apt.izzysoft.de/fdroid/index/apk/cf.playhi.freezeyou)
```

感谢你的帮助和支持！

**Comment by Playhi** [comment]
> 已合并！自动更新的问题之后会解决。大概两到三天内会进入存储库。主存储库徽标
> 
> [<img alt="Get it on F-Droid" height="80" src="https://camo.githubusercontent.com/16dfb987afb6c25d8d861680d279611161f98237503e0607d97e28461a259354/68747470733a2f2f6664726f69642e6769746c61622e696f2f617274776f726b2f62616467652f6765742d69742d6f6e2e706e67">](https://f-droid.org/packages/cf.playhi.freezeyouSome)
> 
> ```
> [<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
>     alt="Get it on F-Droid"
>     height="80">](https://f-droid.org/packages/cf.playhi.freezeyouSome)
> ```
> 
> IzzySoft 存储库的徽标
> 
> [<img alt="Get it on IzzyOnDroid" height="80" src="https://camo.githubusercontent.com/12ce53a3272a486325fcadce4fb282cf7287b24780a36d849a9243206b66cff6/68747470733a2f2f6769746c61622e636f6d2f497a7a794f6e44726f69642f7265706f2f2d2f7261772f6d61737465722f6173736574732f497a7a794f6e44726f69642e706e67">](https://apt.izzysoft.de/fdroid/index/apk/cf.playhi.freezeyou)
> 
> ```
> [<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png"
>     alt="Get it on IzzyOnDroid"
>     height="80">](https://apt.izzysoft.de/fdroid/index/apk/cf.playhi.freezeyou)
> ```
> 
> 感谢你的帮助和支持！

感谢！ :joy: 后续还有什么情况的话随时联系～ :laughing:

**Comment by linsui** [comment]
谢谢！
