### ISSUE TITLE
How do you uninstall this Freeze You! application?

### ISSUE THREAD

**Issue by ez2dj** [FreezeYou/FreezeYou#215]
I installed it with the authority. (adb shell dpm set-device-owner cf.playhi.freezeyou/.DeviceAdminReceiver)

I want to delete Freeze You!
but
I can't cancel the permission from Device Manager app selection.
I can't delete even I try with adb.

![bandicam 2022-03-11 02-00-05-930](https://user-images.githubusercontent.com/53131830/157715587-8a3ae0d4-6a8e-4c08-99c0-5b8a49d3470b.png)

**Comment by Playhi** [comment]
(Already replied in the QQ group :joy: ) 
> (in FreezeYou) Settings - Danger Zone - Release no-root mode permission

We will add something about this situation on the FreezeYou website these days.
