### ISSUE TITLE
App shortcut requires 3 clciks, lower it or make an additinal app shortcut icon for "freeze after quit"

### ISSUE THREAD

**Issue by Tanzin01** [FreezeYou/FreezeYou#221]
**Is your feature request related to a problem? Please describe.**  
Yes. "freeze after quit" options is a bit cucumbersome.  After enabling this option, apps vanishes. Now i can use the option " freeze unfreeze shortcut". However, it requires 3 clciks instead of 1. 

**Describe the solution you'd like**  

Lets say i created a "app shortcut" for my browser. Now if i click it, 2 more pop up confirmation window appears. In total three clicks needed for the app to open. So it would nice to reduce required "clicks". Preferably only 1 click, like other regular apps.

Thanks every people behind it. i just downloaded it today. Its a nice one!

**Comment by Playhi** [comment]
I think we can go to `Settings` - `Freeze and Unfreeze`, and use the `Open Immediately`, `Unfreeze immediately then run when clicking the shortcut`, `Shortcut auto freeze or unfreeze`, `Extra confirmation when freeze`, `Run immediately after unfreezing` options to reach the goal.  
Is this the desired answer?
